In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px
!gdown 1XSg04onQd_esyxUdA3gYCIF0dCeXgVoI

Downloading...
From (original): https://drive.google.com/uc?id=1XSg04onQd_esyxUdA3gYCIF0dCeXgVoI
From (redirected): https://drive.google.com/uc?id=1XSg04onQd_esyxUdA3gYCIF0dCeXgVoI&confirm=t&uuid=47bf258d-3c79-4c0d-af44-e5f73f134493
To: /content/eco2mix-regional-cons-def.csv
100% 320M/320M [00:02<00:00, 114MB/s]

In [ ]:
conso2_df=pd.read_csv("eco2mix-regional-cons-def.csv", sep=";")
conso2_df.head()

<ipython-input-30-d1e3658c4347>:1: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  conso2_df=pd.read_csv("eco2mix-regional-cons-def.csv", sep=";")

,Code INSEE région,Région,Nature,Date,Heure,Date - Heure,Consommation (MW),Thermique (MW),Nucléaire (MW),Eolien (MW),...,TCH Nucléaire (%),TCO Eolien (%),TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%),Column 30
0,27,Bourgogne-Franche-Comté,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,84,Auvergne-Rhône-Alpes,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93,Provence-Alpes-Côte d'Azur,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,76,Occitanie,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,44,Grand Est,Données définitives,2013-01-01,00:00,2013-01-01T00:00:00+01:00,NaN,NaN,NaN,ND,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
conso2_df.tail()

,Code INSEE région,Région,Nature,Date,Heure,Date - Heure,Consommation (MW),Thermique (MW),Nucléaire (MW),Eolien (MW),...,TCH Nucléaire (%),TCO Eolien (%),TCH Eolien (%),TCO Solaire (%),TCH Solaire (%),TCO Hydraulique (%),TCH Hydraulique (%),TCO Bioénergies (%),TCH Bioénergies (%),Column 30
2121403,53,Bretagne,Données consolidées,2023-01-31,23:30,2023-01-31T23:30:00+01:00,3266.0,683.0,0.0,136,...,NaN,4.16,10.42,0.0,0.0,0.34,4.00,1.68,75.34,NaN
2121404,84,Auvergne-Rhône-Alpes,Données consolidées,2023-01-31,23:30,2023-01-31T23:30:00+01:00,8927.0,390.0,13291.0,148,...,97.94,1.66,20.47,0.0,0.0,32.90,25.76,1.25,58.64,NaN
2121405,27,Bourgogne-Franche-Comté,Données consolidées,2023-01-31,23:30,2023-01-31T23:30:00+01:00,2687.0,166.0,0.0,210,...,NaN,7.82,20.45,0.0,0.0,8.19,42.07,1.82,61.25,NaN
2121406,93,Provence-Alpes-Côte d'Azur,Données consolidées,2023-01-31,23:30,2023-01-31T23:30:00+01:00,6139.0,350.0,0.0,44,...,NaN,0.72,45.83,0.0,0.0,30.14,56.68,1.40,28.96,NaN
2121407,52,Pays de la Loire,Données consolidées,2023-01-31,23:30,2023-01-31T23:30:00+01:00,3826.0,172.0,0.0,205,...,NaN,5.36,11.88,0.0,0.0,0.16,60.00,1.52,70.73,NaN

In [ ]:
conso2_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2121408 entries, 0 to 2121407
Data columns (total 32 columns):
 #   Column               Dtype
---  ------               -----
 0   Code INSEE région    int64
 1   Région               object
 2   Nature               object
 3   Date                 object
 4   Heure                object
 5   Date - Heure         object
 6   Consommation (MW)    float64
 7   Thermique (MW)       float64
 8   Nucléaire (MW)       float64
 9   Eolien (MW)          object
 10  Solaire (MW)         float64
 11  Hydraulique (MW)     float64
 12  Pompage (MW)         float64
 13  Bioénergies (MW)     float64
 14  Ech. physiques (MW)  float64
 15  Stockage batterie    float64
 16  Déstockage batterie  float64
 17  Eolien terrestre     float64
 18  Eolien offshore      float64
 19  TCO Thermique (%)    float64
 20  TCH Thermique (%)    float64
 21  TCO Nucléaire (%)    float64
 22  TCH Nucléaire (%)    float64
 23  TCO Eolien (%)       float64
 24  TCH Eolien (%)       float64
 25  TCO Solaire (%)      float64
 26  TCH Solaire (%)      float64
 27  TCO Hydraulique (%)  float64
 28  TCH Hydraulique (%)  float64
 29  TCO Bioénergies (%)  float64
 30  TCH Bioénergies (%)  float64
 31  Column 30            float64
dtypes: float64(25), int64(1), object(6)
memory usage: 517.9+ MB

In [ ]:
conso2_df["Région"].unique()

array(['Bourgogne-Franche-Comté', 'Auvergne-Rhône-Alpes',
       "Provence-Alpes-Côte d'Azur", 'Occitanie', 'Grand Est',
       'Normandie', 'Bretagne', 'Île-de-France', 'Pays de la Loire',
       'Nouvelle-Aquitaine', 'Centre-Val de Loire', 'Hauts-de-France'],
      dtype=object)

In [ ]:
# Calcul du nombre de valeurs nulles par colonne
null_counts = conso2_df.isnull().sum()
print("\nNombre de valeurs nulles par colonne :")
print(null_counts)

Nombre de valeurs nulles par colonne :
Code INSEE région            0
Région                       0
Nature                       0
Date                         0
Heure                        0
Date - Heure                 0
Consommation (MW)           12
Thermique (MW)              12
Nucléaire (MW)          701287
Eolien (MW)                  0
Solaire (MW)                12
Hydraulique (MW)            12
Pompage (MW)            736327
Bioénergies (MW)            12
Ech. physiques (MW)         12
Stockage batterie      1683084
Déstockage batterie    1683084
Eolien terrestre       1683084
Eolien offshore        1683084
TCO Thermique (%)      1472256
TCH Thermique (%)      1472256
TCO Nucléaire (%)      1560096
TCH Nucléaire (%)      1742736
TCO Eolien (%)         1472256
TCH Eolien (%)         1472256
TCO Solaire (%)        1472256
TCH Solaire (%)        1472256
TCO Hydraulique (%)    1472256
TCH Hydraulique (%)    1472256
TCO Bioénergies (%)    1472256
TCH Bioénergies (%)    1472256
Column 30              2121408
dtype: int64

In [ ]:
# Attempt to convert to numeric, non-numeric values will become NaN
conso2_df['numeric_column'] = pd.to_numeric(conso2_df["Eolien (MW)"], errors='coerce')

# Identify non-numeric values
non_numeric_values = conso2_df[conso2_df['numeric_column'].isna()]["Eolien (MW)"]

# Print non-numeric values
print("Valeurs non numériques dans la colonne 'Eolien':")
print(non_numeric_values)
print(non_numeric_values.unique())

Valeurs non numériques dans la colonne 'Eolien':
0         ND
1         ND
2         ND
3         ND
4         ND
          ..
207895     -
207910     -
207918     -
207928     -
207940     -
Name: Eolien (MW), Length: 108, dtype: object
['ND' '-']

In [ ]:
# Remplacer "ND" et "-" par des chaînes vides dans la colonne "Eolien (MW)"
conso2_df["Eolien (MW)"].replace(["ND", "-"], "", inplace=True)

In [ ]:
conso2_df["Eolien (MW)"] = pd.to_numeric(conso2_df["Eolien (MW)"], errors='coerce')

In [ ]:
conso2_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2121408 entries, 0 to 2121407
Data columns (total 33 columns):
 #   Column               Dtype
---  ------               -----
 0   Code INSEE région    int64
 1   Région               object
 2   Nature               object
 3   Date                 object
 4   Heure                object
 5   Date - Heure         object
 6   Consommation (MW)    float64
 7   Thermique (MW)       float64
 8   Nucléaire (MW)       float64
 9   Eolien (MW)          float64
 10  Solaire (MW)         float64
 11  Hydraulique (MW)     float64
 12  Pompage (MW)         float64
 13  Bioénergies (MW)     float64
 14  Ech. physiques (MW)  float64
 15  Stockage batterie    float64
 16  Déstockage batterie  float64
 17  Eolien terrestre     float64
 18  Eolien offshore      float64
 19  TCO Thermique (%)    float64
 20  TCH Thermique (%)    float64
 21  TCO Nucléaire (%)    float64
 22  TCH Nucléaire (%)    float64
 23  TCO Eolien (%)       float64
 24  TCH Eolien (%)       float64
 25  TCO Solaire (%)      float64
 26  TCH Solaire (%)      float64
 27  TCO Hydraulique (%)  float64
 28  TCH Hydraulique (%)  float64
 29  TCO Bioénergies (%)  float64
 30  TCH Bioénergies (%)  float64
 31  Column 30            float64
 32  numeric_column       float64
dtypes: float64(27), int64(1), object(5)
memory usage: 534.1+ MB

In [ ]:
conso2_df['Date - Heure'] = pd.to_datetime(conso2_df['Date - Heure'], errors='coerce')
print(conso2_df['Date - Heure'].dtype)

object

In [ ]:
conso2_df['time_bins'] = conso2_df['Date - Heure'].dt.floor('2h')
grouped_conso2h_df=conso2_df.groupby(['time_bins', 'Région'])[['Consommation (MW)', 'Thermique (MW)', 'Nucléaire (MW)', 'Eolien (MW)', 'Solaire (MW)', 'Hydraulique (MW)', 'Bioénergies (MW)']].sum().reset_index()
grouped_conso2h_df.head()

AttributeError: Can only use .dt accessor with datetimelike values

In [ ]:
grouped_conso2h_df.tail()

In [ ]:
grouped_conso2h_df.to_csv("Conso_région_group2h.csv", index=False)

In [ ]:
import os

file_size = os.path.getsize('/content/Conso_région_group2h.csv')
print("file size :", file_size, "bytes")